AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  
Metrics/AbcSize:
  Max: 20  # Увеличиваем лимит с 17 до 20
  Exclude:
    - 'spec/**/*.rb'

# Игнорируем проверку длины блоков в тестах
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

# Разрешаем длинные строки в тестах
Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'

# Разрешаем большие классы в тестах
Metrics/ClassLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/EndOfLine:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
