AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
  SuggestExtensions: false

Layout/EndOfLine:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes